### ISSUE TITLE
Filesystem paths can now be extracted from the API

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/powerstrip-flocker#2]
https://clusterhq.atlassian.net/browse/FLOC-1460 is now finished, so `GET /v1/state/datasets` now includes paths in its output.

**Comment by lukemarsden** [comment]
Thank you for this! I will leave this issue open until I get a chance to do another pass over powerstrip-flocker (or the eventual Docker extension it will become).

**Comment by lukemarsden** [comment]
Fixed in https://github.com/ClusterHQ/powerstrip-flocker/commit/4b85f8279646613ae037c2edb712a95aec2d2cbc :smile:
